services:
  postgres-db:
    container_name: postgresDb-detailpage
    image: postgres:16.0
    environment:
      POSTGRES_USER: detailpage
      POSTGRES_PASSWORD: password
      POSTGRES_DB: detailpage_db
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '25433:5432'
    volumes:
      - postgres-data-detail-page:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - detail-page-network

volumes:
  postgres-data-detail-page:

networks:
  detail-page-network:
    driver: bridge

